import { User, Member, Transaction, InventoryItem, Event, DashboardStats, ChartData } from '../types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@igreja.org',
    role: 'admin',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Manager User',
    email: 'manager@igreja.org',
    role: 'manager',
    createdAt: '2024-02-10T14:30:00Z',
  },
  {
    id: '3',
    name: 'Viewer User',
    email: 'viewer@igreja.org',
    role: 'viewer',
    createdAt: '2024-03-05T09:15:00Z',
  },
];

// Mock Members
export const mockMembers: Member[] = [
  {
    id: '1',
    firstName: 'João',
    lastName: 'Silva',
    email: 'joao.silva@email.com',
    phone: '(11) 98765-4321',
    address: 'Rua das Flores, 123, São Paulo - SP',
    birthDate: '1985-06-15',
    baptismDate: '2005-08-20',
    joinDate: '2010-03-10',
    status: 'active',
    groups: ['Jovens', 'Música'],
    ministries: ['Louvor'],
    skills: ['Violão', 'Vocal'],
    photo: 'https://randomuser.me/api/portraits/men/1.jpg',
    notes: 'Membro ativo no ministério de louvor',
  },
  {
    id: '2',
    firstName: 'Maria',
    lastName: 'Santos',
    email: 'maria.santos@email.com',
    phone: '(11) 91234-5678',
    address: 'Av. Paulista, 1000, São Paulo - SP',
    birthDate: '1990-02-25',
    baptismDate: '2012-05-12',
    joinDate: '2015-01-05',
    status: 'active',
    groups: ['Mulheres', 'Educação'],
    ministries: ['Escola Dominical'],
    skills: ['Ensino', 'Organização'],
    photo: 'https://randomuser.me/api/portraits/women/2.jpg',
    notes: 'Professora de escola dominical para crianças',
  },
  {
    id: '3',
    firstName: 'Pedro',
    lastName: 'Oliveira',
    email: 'pedro.oliveira@email.com',
    phone: '(11) 94567-8901',
    address: 'Rua Bela Vista, 45, São Paulo - SP',
    birthDate: '1978-11-30',
    baptismDate: '2000-04-09',
    joinDate: '2008-07-22',
    status: 'active',
    groups: ['Homens', 'Administração'],
    ministries: ['Diáconos'],
    skills: ['Liderança', 'Administração'],
    photo: 'https://randomuser.me/api/portraits/men/3.jpg',
    notes: 'Diácono responsável pela administração',
  },
  {
    id: '4',
    firstName: 'Ana',
    lastName: 'Costa',
    email: 'ana.costa@email.com',
    phone: '(11) 95678-9012',
    address: 'Rua dos Girassóis, 78, São Paulo - SP',
    birthDate: '1995-04-18',
    joinDate: '2020-02-15',
    status: 'visitor',
    groups: ['Jovens'],
    ministries: [],
    skills: ['Design', 'Fotografia'],
    photo: 'https://randomuser.me/api/portraits/women/4.jpg',
    notes: 'Visitante regular interessada em batismo',
  },
  {
    id: '5',
    firstName: 'Carlos',
    lastName: 'Ferreira',
    email: 'carlos.ferreira@email.com',
    phone: '(11) 96789-0123',
    address: 'Rua das Palmeiras, 234, São Paulo - SP',
    birthDate: '1982-09-07',
    baptismDate: '2003-11-16',
    joinDate: '2012-10-05',
    status: 'inactive',
    groups: ['Música'],
    ministries: ['Louvor'],
    skills: ['Bateria', 'Percussão'],
    photo: 'https://randomuser.me/api/portraits/men/5.jpg',
    notes: 'Membro inativo desde janeiro de 2023',
  },
];

// Mock Transactions
export const mockTransactions: Transaction[] = [
  {
    id: '1',
    memberId: '1',
    memberName: 'João Silva',
    type: 'tithe',
    amount: 500,
    date: '2024-04-01T10:15:00Z',
    category: 'Regular',
    description: 'Dízimo mensal',
    paymentMethod: 'pix',
  },
  {
    id: '2',
    memberId: '2',
    memberName: 'Maria Santos',
    type: 'offering',
    amount: 200,
    date: '2024-04-02T09:30:00Z',
    category: 'Culto de Domingo',
    paymentMethod: 'cash',
  },
  {
    id: '3',
    memberId: '3',
    memberName: 'Pedro Oliveira',
    type: 'donation',
    amount: 1000,
    date: '2024-04-05T14:45:00Z',
    category: 'Projeto Missões',
    description: 'Doação para projeto missionário',
    paymentMethod: 'transfer',
  },
  {
    id: '4',
    type: 'expense',
    amount: 350,
    date: '2024-04-06T11:20:00Z',
    category: 'Manutenção',
    description: 'Conserto do ar-condicionado',
    paymentMethod: 'card',
  },
  {
    id: '5',
    type: 'expense',
    amount: 1250,
    date: '2024-04-08T13:10:00Z',
    category: 'Salários',
    description: 'Pagamento funcionários administrativos',
    paymentMethod: 'transfer',
  },
  {
    id: '6',
    memberId: '1',
    memberName: 'João Silva',
    type: 'tithe',
    amount: 500,
    date: '2024-05-01T10:20:00Z',
    category: 'Regular',
    description: 'Dízimo mensal',
    paymentMethod: 'pix',
  },
  {
    id: '7',
    type: 'expense',
    amount: 180,
    date: '2024-05-03T15:40:00Z',
    category: 'Materiais',
    description: 'Material escolar para aulas dominicais',
    paymentMethod: 'card',
  },
];

// Mock Inventory
export const mockInventory: InventoryItem[] = [
  {
    id: '1',
    name: 'Bíblias para Estudo',
    category: 'Literatura',
    quantity: 50,
    location: 'Almoxarifado A',
    value: 50,
    supplier: 'Editora Cristã',
    purchaseDate: '2024-01-10',
    minQuantity: 10,
    status: 'available',
    notes: 'Bíblias novas para distribuição',
  },
  {
    id: '2',
    name: 'Microfones sem fio',
    category: 'Equipamento',
    quantity: 5,
    location: 'Sala de Som',
    value: 350,
    supplier: 'AudioPro',
    purchaseDate: '2023-11-15',
    minQuantity: 2,
    status: 'available',
    notes: 'Microfones para uso no culto',
  },
  {
    id: '3',
    name: 'Cadeiras',
    category: 'Mobiliário',
    quantity: 200,
    location: 'Salão Principal',
    value: 75,
    supplier: 'MóveisGrande',
    purchaseDate: '2023-06-20',
    minQuantity: 150,
    status: 'available',
    notes: 'Cadeiras para auditório',
  },
  {
    id: '4',
    name: 'Material de Limpeza',
    category: 'Consumíveis',
    quantity: 8,
    location: 'Depósito B',
    value: 15,
    supplier: 'CleanPlus',
    purchaseDate: '2024-03-05',
    minQuantity: 10,
    status: 'low',
    notes: 'Estoque baixo, precisa repor',
  },
  {
    id: '5',
    name: 'Caixas de Som',
    category: 'Equipamento',
    quantity: 2,
    location: 'Sala de Som',
    value: 1200,
    supplier: 'AudioPro',
    purchaseDate: '2023-08-12',
    minQuantity: 2,
    status: 'available',
    notes: 'Caixas amplificadas',
  },
];

// Mock Events
export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Culto de Domingo',
    startDate: '2024-05-12T09:00:00Z',
    endDate: '2024-05-12T12:00:00Z',
    description: 'Culto dominical regular',
    location: 'Templo Principal',
    status: 'planned',
    organizer: 'Pastor José',
    resources: [
      { id: '1', name: 'Sistema de Som', type: 'equipment', quantity: 1 },
      { id: '2', name: 'Equipe de Louvor', type: 'personnel', quantity: 5 },
    ],
  },
  {
    id: '2',
    title: 'Encontro de Jovens',
    startDate: '2024-05-18T19:00:00Z',
    endDate: '2024-05-18T22:30:00Z',
    description: 'Encontro mensal dos jovens',
    location: 'Salão Social',
    budget: 500,
    status: 'planned',
    organizer: 'Líder de Jovens',
    resources: [
      { id: '1', name: 'Sistema de Som', type: 'equipment', quantity: 1 },
      { id: '2', name: 'Projetor', type: 'equipment', quantity: 1 },
      { id: '3', name: 'Equipe de Apoio', type: 'personnel', quantity: 3 },
    ],
  },
  {
    id: '3',
    title: 'Estudo Bíblico',
    startDate: '2024-05-15T19:30:00Z',
    endDate: '2024-05-15T21:00:00Z',
    description: 'Estudo bíblico semanal',
    location: 'Sala de Estudos',
    status: 'planned',
    organizer: 'Pastor Auxiliar',
    resources: [
      { id: '1', name: 'Bíblias de Estudo', type: 'equipment', quantity: 20 },
      { id: '2', name: 'Apostilas', type: 'equipment', quantity: 20 },
    ],
  },
  {
    id: '4',
    title: 'Retiro Espiritual',
    startDate: '2024-06-14T17:00:00Z',
    endDate: '2024-06-16T14:00:00Z',
    description: 'Retiro anual para membros da igreja',
    location: 'Chácara Recanto',
    budget: 5000,
    status: 'planned',
    organizer: 'Comissão de Eventos',
    resources: [
      { id: '1', name: 'Transporte', type: 'equipment', quantity: 2 },
      { id: '2', name: 'Equipe de Louvor', type: 'personnel', quantity: 5 },
      { id: '3', name: 'Equipe de Cozinha', type: 'personnel', quantity: 3 },
    ],
  },
  {
    id: '5',
    title: 'Reunião de Liderança',
    startDate: '2024-05-10T19:00:00Z',
    endDate: '2024-05-10T21:00:00Z',
    description: 'Reunião mensal com líderes de ministérios',
    location: 'Sala de Reuniões',
    status: 'completed',
    organizer: 'Pastor Principal',
    resources: [
      { id: '1', name: 'Projetor', type: 'equipment', quantity: 1 },
      { id: '2', name: 'Material de Apoio', type: 'equipment', quantity: 15 },
    ],
  },
];

// Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalMembers: 120,
  activeMembersPercentage: 85,
  newMembersThisMonth: 4,
  totalIncome: 12500,
  totalExpenses: 8300,
  upcomingEvents: 8,
  lowStockItems: 3,
};

// Chart Data
export const mockMembershipChart: ChartData = {
  labels: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun'],
  datasets: [
    {
      label: 'Novos Membros',
      data: [3, 5, 2, 4, 6, 3],
      backgroundColor: 'rgba(0, 59, 77, 0.7)',
    },
  ],
};

export const mockFinanceChart: ChartData = {
  labels: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun'],
  datasets: [
    {
      label: 'Receitas',
      data: [10500, 11200, 9800, 12500, 10800, 11500],
      borderColor: 'rgba(212, 175, 55, 0.7)',
      backgroundColor: 'rgba(212, 175, 55, 0.2)',
    },
    {
      label: 'Despesas',
      data: [7800, 8100, 7500, 8300, 7900, 8200],
      borderColor: 'rgba(239, 68, 68, 0.7)',
      backgroundColor: 'rgba(239, 68, 68, 0.2)',
    },
  ],
};

export const mockAttendanceChart: ChartData = {
  labels: ['Domingo', 'Quarta', 'Sexta', 'Células', 'Jovens'],
  datasets: [
    {
      label: 'Presenças',
      data: [95, 45, 60, 80, 35],
      backgroundColor: [
        'rgba(0, 59, 77, 0.8)',
        'rgba(212, 175, 55, 0.8)',
        'rgba(59, 130, 246, 0.8)',
        'rgba(16, 185, 129, 0.8)',
        'rgba(245, 158, 11, 0.8)',
      ],
    },
  ],
};